name: CI - PHP CRUD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo, mysql
        coverage: none

    # 👇 En lugar de composer, valida solo sintaxis PHP
    - name: Validar sintaxis PHP
      run: |
        find . -type f -name "*.php" -exec php -l {} \;
