name: CI - PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalar dependencias
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Ejecutar pruebas
        run: vendor/bin/phpunit --testdox

