<?php

class Workflow {
    private $steps = [];
    
    // Añadir paso al workflow
    public function addStep(callable $step) {
        $this->steps[] = $step;
    }

    // Ejecutar el flujo completo
    public function run($data) {
        foreach ($this->steps as $step) {
            $data = $step($data); // cada paso puede modificar los datos
        }
        return $data;
    }
}

// Ejemplo de pasos ---------------------

// 1. Validar datos
$validar = function($data) {
    if (empty($data['nombre'])) {
        throw new Exception("El nombre es obligatorio");
    }
    return $data;
};

// 2. Procesar (ejemplo: poner en mayúsculas)
$procesar = function($data) {
    $data['nombre'] = strtoupper($data['nombre']);
    return $data;
};

// 3. Notificar (ejemplo: log simple)
$notificar = function($data) {
    echo "Notificación: Se procesó el usuario {$data['nombre']}\n";
    return $data;
};

// ---------------------
// Uso del workflow
// ---------------------

try {
    $workflow = new Workflow();
    $workflow->addStep($validar);
    $workflow->addStep($procesar);
    $workflow->addStep($notificar);

    $resultado = $workflow->run([
        "nombre" => "Carlos"
    ]);

    print_r($resultado);

} catch (Exception $e) {
    echo "Error en el workflow: " . $e->getMessage();
}

